
USE QLDT

-- Q58. Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề.

-- C1: EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT CD.MACD 
					FROM CHUDE CD
					EXCEPT
					SELECT DT.MACD
					FROM DETAI DT JOIN THAMGIADT TGDT ON DT.MADT = TGDT.MADT
					WHERE GV.MAGV=TGDT.MAGV)

-- C2: NOT EXIST
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
					FROM CHUDE CD
					WHERE NOT EXISTS(
					SELECT *
					FROM DETAI DT JOIN THAMGIADT TGDT ON DT.MADT = TGDT.MADT
					WHERE GV.MAGV=TGDT.MAGV AND CD.MACD = DT.MACD ))

-- C3: COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
				JOIN DETAI DT ON TG.MADT = DT.MADT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MACD) = (SELECT COUNT (CD.MACD) FROM CHUDE CD)

--Q59. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn HTTT tham gia.
-- C1: EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ((SELECT MAGV FROM GIAOVIEN WHERE MABM = 'HTTT')
					EXCEPT 
					(SELECT MAGV FROM THAMGIADT WHERE DT.MADT = MADT))

-- C2: NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT * FROM GIAOVIEN GV WHERE GV.MABM = 'HTTT' 
					AND NOT EXISTS (SELECT * FROM THAMGIADT TG 
										WHERE TG.MADT = DT.MADT AND GV.MAGV = TG.MAGV))

-- C3: COUNT 
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
				JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
WHERE GV.MABM = 'HTTT'
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(*) FROM GIAOVIEN GV WHERE GV.MABM = 'HTTT')

--Q60. Cho biết tên đề tài có tất cả giảng viên bộ môn “Hệ thống thông tin” tham gia
-- C1: EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ((SELECT GV.MAGV 
					FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM
					WHERE BM.TENBM = N'Hệ thống thông tin')
					EXCEPT 
					(SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MADT = DT.MADT))

-- C2: NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT * 
					FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM
					WHERE BM.TENBM = N'Hệ thống thông tin' 
					AND NOT EXISTS (SELECT * FROM THAMGIADT TG WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))

-- C3: COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
				JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
				JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.TENBM = N'Hệ thống thông tin'  
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(*)
								  FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
							      WHERE BM.TENBM = N'Hệ thống thông tin'  )

--Q61. Cho biết giáo viên nào đã tham gia tất cả các đề tài có mã chủ đề là QLGD.
-- C1: EXCEPT
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS ((SELECT DT.MADT FROM DETAI DT WHERE DT.MACD = 'QLGD')
					EXCEPT (SELECT MADT FROM THAMGIADT WHERE MAGV = GV.MAGV))

-- C2: NOT EXISTS
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT DT.* 
					FROM DETAI DT 
					WHERE DT.MACD = 'QLGD' 
						AND NOT EXISTS (SELECT TG.* 
										FROM THAMGIADT TG
										WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT ))
					
-- C3: COUNT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
				JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE DT.MACD = 'QLGD' 
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT)=(SELECT COUNT(*) 
								FROM DETAI DT
								WHERE DT.MACD = 'QLGD'	)
--Q62. Cho biết tên giáo viên nào tham gia tất cả các đề tài mà giáo viên Trần Trà Hương đã
--tham gia.
-- C1: EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.HOTEN!=N'Trần Trà Hương' AND NOT EXISTS (SELECT TG.MADT
												  FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV=GV.MAGV
												  WHERE GV.HOTEN=N'Trần Trà Hương'
												  EXCEPT
												  SELECT TG.MADT
												  FROM THAMGIADT TG 
												  WHERE TG.MAGV=GV.MAGV)
					
-- C2: NOT EXISTS					
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.HOTEN != N'Trần Trà Hương' AND NOT EXISTS (SELECT * 
												    FROM THAMGIADT TG1 JOIN GIAOVIEN GV1 ON TG1.MAGV = GV1.MAGV
													WHERE GV1.HOTEN = N'Trần Trà Hương'
															AND NOT EXISTS (SELECT * 
																			FROM THAMGIADT TG
																			WHERE TG.MAGV = GV.MAGV AND TG.MADT = TG1.MADT))
-- C3: COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE GV.HOTEN != N'Trần Trà Hương' AND TG.MADT IN (SELECT TG.MADT 
													FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
													WHERE GV.HOTEN = N'Trần Trà Hương')
													
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT (TG.MADT) 
								  FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
								  WHERE GV.HOTEN = N'Trần Trà Hương')

--Q63. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn Hóa Hữu Cơ tham gia.
-- C1: EXCEPT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON TG.MADT = DT.MADT
			  JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
			  JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.TENBM = N'Hóa Hữu Cơ' 
	AND NOT EXISTS (SELECT GV.MAGV 
				    FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				    WHERE BM.TENBM = N'Hóa Hữu Cơ'
				    EXCEPT
				   (SELECT TG.MAGV 
				    FROM THAMGIADT TG 
					WHERE TG.MADT = DT.MADT))

-- C2: NOT EXIST
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON TG.MADT = DT.MADT
			  JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
			  JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.TENBM = N'Hóa Hữu Cơ' 
	AND NOT EXISTS (SELECT *
					FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
					WHERE BM.TENBM = N'Hóa Hữu Cơ'
				    AND NOT EXISTS
						(SELECT *
						FROM THAMGIADT TG 
						WHERE TG.MADT = DT.MADT AND TG.MAGV = GV.MAGV))

-- C3: COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON TG.MADT = DT.MADT
			  JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
			  JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.TENBM = N'Hóa Hữu Cơ' 
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(*)
								  FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
								  WHERE BM.TENBM  = N'Hóa Hữu Cơ' )

--Q64. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 006.
-- C1: EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT CV.MADT, CV.SOTT
				  FROM CONGVIEC CV JOIN THAMGIADT TG ON TG.MADT = CV.MADT AND CV.SOTT = TG.STT
				  WHERE CV.MADT='006'
				  EXCEPT
				  (SELECT CV.MADT, CV.SOTT
				  FROM CONGVIEC CV JOIN THAMGIADT TG ON TG.MADT = CV.MADT AND CV.SOTT = TG.STT
				  WHERE TG.MAGV = GV.MAGV))

-- C2: NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT *
				  FROM CONGVIEC CV1 JOIN THAMGIADT TG1 ON TG1.MADT = CV1.MADT AND CV1.SOTT = TG1.STT
				  WHERE CV1.MADT='006'
					AND NOT EXISTS
				  (SELECT *
				  FROM CONGVIEC CV2 JOIN THAMGIADT TG2 ON TG2.MADT = CV2.MADT AND CV2.SOTT = TG2.STT
				  WHERE TG2.MAGV = GV.MAGV AND CV2.MADT = CV1.MADT AND CV1.SOTT = CV2.SOTT))


-- C3: COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
				 JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT
WHERE TG.MADT = '006'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT CV.SOTT) = (SELECT COUNT(*)
								  FROM CONGVIEC 
								  WHERE MADT = '006')

--Q65. Cho biết giáo viên nào đã tham gia tất cả các đề tài của chủ đề Ứng dụng công nghệ.
-- C1: EXCEPT
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT DT.MADT
				  FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
				  WHERE CD.TENCD = N'Ứng dụng công nghệ'
				  EXCEPT 
				  (SELECT TG.MADT
				   FROM THAMGIADT TG 
				   WHERE TG.MAGV = GV.MAGV))
-- C2: NOT EXISTS
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
				  FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
				  WHERE CD.TENCD = N'Ứng dụng công nghệ'
				  AND NOT EXISTS
					  (SELECT *
					   FROM THAMGIADT TG 
					   WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))

-- C3: COUNT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
				 JOIN DETAI DT ON TG.MADT = DT.MADT
				 JOIN CHUDE CD ON CD.MACD = DT.MACD
WHERE CD.TENCD = N'Ứng dụng công nghệ'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(*) 
								  FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
								  WHERE CD.TENCD = N'Ứng dụng công nghệ')

--Q66. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài của do Trần Trà Hương làm chủ
--nhiệm.
-- C1: EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT DT.MADT
				  FROM DETAI DT JOIN GIAOVIEN GVCN ON DT.GVCNDT = GVCN.MAGV
				  WHERE GVCN.HOTEN = N'Trần Trà Hương'
				  EXCEPT
				  (SELECT TG.MADT
				   FROM THAMGIADT TG 
				   WHERE TG.MAGV = GV.MAGV))
--
SELECT DISTINCT GV.HOTEN
FROM THAMGIADT TG1 JOIN GIAOVIEN GV ON TG1.MAGV = GV.MAGV
WHERE NOT EXISTS (SELECT DT.MADT
				  FROM DETAI DT JOIN GIAOVIEN GVCN ON DT.GVCNDT = GVCN.MAGV
				  WHERE GVCN.HOTEN = N'Trần Trà Hương'
				  EXCEPT
				  (SELECT TG2.MADT
				   FROM THAMGIADT TG2 
				   WHERE TG2.MAGV = TG1.MAGV))
-- C2: NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT *
				  FROM DETAI DT JOIN GIAOVIEN GVCN ON DT.GVCNDT = GVCN.MAGV
				  WHERE GVCN.HOTEN = N'Trần Trà Hương'
					AND NOT EXISTS
					  (SELECT *
					   FROM THAMGIADT TG 
					   WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))

-- C3: COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
				 JOIN DETAI DT ON DT.MADT = TG.MADT
				 JOIN GIAOVIEN GVCN ON DT.GVCNDT = GVCN.MAGV
WHERE GVCN.HOTEN = N'Trần Trà Hương'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(*)
								  FROM DETAI DT JOIN GIAOVIEN GVCN ON DT.GVCNDT = GVCN.MAGV
								  WHERE GVCN.HOTEN = N'Trần Trà Hương')

SELECT GV.HOTEN
FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
				 JOIN DETAI DT ON DT.MADT = TG.MADT
				 JOIN GIAOVIEN GVCN ON DT.GVCNDT = GVCN.MAGV
WHERE GVCN.HOTEN = N'Trần Trà Hương'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DT.MADT)
								  FROM DETAI DT JOIN GIAOVIEN GVCN ON DT.GVCNDT = GVCN.MAGV
								  WHERE GVCN.HOTEN = N'Trần Trà Hương')
--Q67. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa CNTT tham gia.
-- C1: EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT GV.MAGV 
				  FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM
				  WHERE BM.MAKHOA = 'CNTT'
				  EXCEPT
				  (SELECT TG.MAGV 
				   FROM THAMGIADT TG 
				   WHERE TG.MADT = DT.MADT))

-- C2: NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
				  FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM
				  WHERE BM.MAKHOA = 'CNTT'
				  AND NOT EXISTS
				  (SELECT *
				   FROM THAMGIADT TG 
				   WHERE TG.MADT = DT.MADT AND TG.MAGV = GV.MAGV))

-- C3: COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
			  JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
			  JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.MAKHOA = 'CNTT'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT (*)
								  FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
								  WHERE BM.MAKHOA = 'CNTT')

--Q68. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài Nghiên cứu tế
--bào gốc.
-- C1: EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT CV.MADT, CV.SOTT
				  FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
				  WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
				  EXCEPT
				  SELECT TG.MADT, TG.STT
				  FROM THAMGIADT TG WHERE TG.MAGV = GV.MAGV)

SELECT DISTINCT GV.HOTEN
FROM THAMGIADT TG1 JOIN GIAOVIEN GV ON TG1.MAGV = GV.MAGV
WHERE NOT EXISTS (SELECT CV.MADT, CV.SOTT
				  FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
				  WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
				  EXCEPT
				  SELECT TG2.MADT, TG2.STT
				  FROM THAMGIADT TG2 WHERE TG2.MAGV = GV.MAGV)
-- C2: NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
				  FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
				  WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
				  AND NOT EXISTS
				  (SELECT *
				  FROM THAMGIADT TG WHERE TG.MAGV = GV.MAGV AND TG.MADT = CV.MADT AND TG.STT = CV.SOTT))

-- C3: COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
				 JOIN CONGVIEC CV ON CV.MADT = TG.MADT AND CV.SOTT = TG.STT
				 JOIN DETAI DT ON CV.MADT = DT.MADT
WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.STT) = (SELECT COUNT(*)
								 FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
								 WHERE DT.TENDT = N'Nghiên cứu tế bào gốc')

--Q69. Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu?
-- C1: EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT DT.MADT 
				  FROM DETAI DT
				  WHERE DT.KINHPHI > 100
				  EXCEPT 
				  SELECT TG.MADT
				  FROM THAMGIADT TG
				  WHERE TG.MAGV = GV.MAGV)
-- C2: NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT * 
				  FROM DETAI DT
				  WHERE DT.KINHPHI > 100
				  AND NOT EXISTS
				  (SELECT *
				  FROM THAMGIADT TG
				  WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))

-- C3: COUNT
SELECT GV.HOTEN 
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
				 JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.KINHPHI > 100
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(*) 
								  FROM DETAI DT
								  WHERE DT.KINHPHI > 100)

--Q70. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa Sinh Học tham gia.
-- C1: EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT GV.MAGV
				  FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
								   JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
				  WHERE K.TENKHOA = N'Sinh học'
				  EXCEPT
				  SELECT TG.MAGV
				  FROM THAMGIADT TG
				  WHERE TG.MADT = DT.MADT)

-- C2: NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
				  FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
								   JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
				  WHERE K.TENKHOA = N'Sinh học'
				  AND NOT EXISTS
				  (SELECT *
				  FROM THAMGIADT TG
				  WHERE TG.MADT = DT.MADT AND TG.MAGV = GV.MAGV))

-- C3: COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
			  JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
			  JOIN BOMON BM ON GV.MABM = BM.MABM
			  JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Sinh học'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(*)
								  FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
												   JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
								  WHERE K.TENKHOA = N'Sinh học')

--Q71. Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả các công việc của đề tài
--“Ứng dụng hóa học xanh”.
-- C1: EXCEPT
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
				 JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND NOT EXISTS (SELECT CV.SOTT, CV.MADT
														  FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
														  WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
														  EXCEPT 
														  SELECT TG.STT, TG.MADT
														  FROM THAMGIADT TG 
														  WHERE TG.MAGV = GV.MAGV)

-- C2: NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
				 JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND NOT EXISTS (SELECT *
														  FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
														  WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
														  AND NOT EXISTS
														  (SELECT TG.STT, TG.MADT
														  FROM THAMGIADT TG 
														  WHERE TG.MAGV = GV.MAGV AND TG.MADT = CV.MADT AND TG.STT = CV.SOTT))

-- C3: COUNT:
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
				 JOIN DETAI DT ON TG.MADT = DT.MADT
				 JOIN CONGVIEC CV ON CV.MADT = TG.MADT AND CV.SOTT = TG.STT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(DISTINCT TG.STT) = (SELECT COUNT(*)
								 FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT 
								  WHERE DT.TENDT = N'Ứng dụng hóa học xanh')

--Q72. Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn của giáo viên
--tham gia tất cả các đề tài thuộc chủ đề “Nghiên cứu phát triển”.
-- C1: EXCEPT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
WHERE NOT EXISTS (SELECT DT.MADT
				  FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
				  WHERE CD.TENCD = N'Nghiên cứu phát triển'
				  EXCEPT 
				  SELECT TG.MADT
				  FROM THAMGIADT TG
				  WHERE TG.MAGV = GV.MAGV)

USE QLDT
SELECT TG1.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
FROM THAMGIADT TG1 JOIN GIAOVIEN GV ON GV.MAGV = TG1.MAGV
					JOIN BOMON BM ON GV.MABM = BM.MABM
					JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
WHERE NOT EXISTS ((SELECT DT.MADT
					FROM DETAI DT JOIN CHUDE CD ON CD.MACD = DT.MACD
					WHERE CD.TENCD = N'Nghiên cứu phát triển')

					EXCEPT

					(SELECT TG2.MADT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = TG1.MAGV))
-- C2: NOT EXISTS 
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
WHERE NOT EXISTS (SELECT *
				  FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
				  WHERE CD.TENCD = N'Nghiên cứu phát triển'
				  AND NOT EXISTS 
				  (SELECT *
				  FROM THAMGIADT TG
				  WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))

-- C3: COUNT.
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
				 JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
				 JOIN DETAI DT ON TG.MADT = DT.MADT
				 JOIN CHUDE CD ON CD.MACD = DT.MACD
WHERE CD.TENCD = N'Nghiên cứu phát triển'
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(*) 
								  FROM DETAI DT JOIN CHUDE CD ON CD.MACD = DT.MACD
								  WHERE CD.TENCD = N'Nghiên cứu phát triển' )
--
SELECT TG1.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
FROM THAMGIADT TG1 JOIN GIAOVIEN GV ON TG1.MAGV = GV.MAGV
					JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
				 JOIN DETAI DT ON TG1.MADT = DT.MADT
				 JOIN CHUDE CD ON CD.MACD = DT.MACD
WHERE CD.TENCD = N'Nghiên cứu phát triển'
GROUP BY TG1.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
HAVING COUNT(DISTINCT TG1.MADT) = (SELECT COUNT(DT.MADT) 
								  FROM DETAI DT JOIN CHUDE CD ON CD.MACD = DT.MACD
								  WHERE CD.TENCD = N'Nghiên cứu phát triển' )