
USE QLDT

--1. CHO BIẾT GIÁO VIÊN THAM GIA ĐỀ TÀI BẮT ĐẦU VÀ KẾT THÚC TRONG NĂM 2008
select DISTINCT GV.*
from GIAOVIEN GV 
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
JOIN CONGVIEC CV ON TGDT.MADT = CV.MADT
where year(CV.NGAYBD) = 2008 and year(CV.NGAYKT)=2008
SELECT * FROM BOMON

--2. CHO BIẾT MABM, TÊN BM, HỌ TÊN TRƯỞNG BM, SỐ GIÁO VIÊN CỦA BỘ MÔN CÓ TRƯỞNG BM NHẬN CHỨC TRONG THÁNG 2/2000

select BM.MABM, BM.TENBM, TBM.HOTEN HOTENTRUONGBM, BM.NGAYNHANCHUC, count(GV.MAGV) SOGV
from BOMON BM JOIN GIAOVIEN TBM ON BM.TRUONGBM = TBM.MAGV
JOIN GIAOVIEN GV ON GV.MABM = BM.MABM
where BM.NGAYNHANCHUC between '1/1/2007' and '12/31/2007' 
group by BM.MABM, BM.TENBM, TBM.HOTEN, BM.NGAYNHANCHUC


--3. CHO BIẾT TÊN BM, LƯƠNG TRUNG BÌNH VÀ SỐ LƯỢNG GIÁO VIÊN CỦA BM CÓ TRƯỞNG BM HỌ "NGUYỄN" TÊN "AN"
SELECT DISTINCT BM.TENBM, AVG(GV.LUONG) AVGLUONG, COUNT(GV.MAGV) SOGV
FROM BOMON BM JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
JOIN GIAOVIEN TBM ON BM.TRUONGBM=TBM.MAGV
WHERE TBM.HOTEN LIKE N'Nguyễn % An'
GROUP BY BM.TENBM

--4. CHO BIẾT TÊN GV, SỐ GIÁO VIÊN QUẢN LÝ VÀ SỐ ĐỀ TÀI CHỦ NHIỆM
SELECT GV.HOTEN, COUNT(DISTINCT GV.GVQLCM) SOGVQL, COUNT(DISTINCT DT.GVCNDT) SODTCN
FROM GIAOVIEN GV LEFT JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY GV.HOTEN






